### ISSUE TITLE
LLVM=1 only

### ISSUE THREAD

**Issue by nickdesaulniers** [Peppe289/builder-linux#1]
From the readme:

> After [Clang LTO Changes](https://github.com/Peppe289/builder-linux/commit/77777e8a7d4f86bcbc5583625f830be421f59a8e) we need to use CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 flags:

Note that only LLVM=1 should be necessary; it implies the rest.

https://docs.kernel.org/kbuild/llvm.html#llvm-utilities

(assuming you're not on some ancient kernel version)

**Comment by Peppe289** [comment]
> From the readme:
> 
> > After [Clang LTO Changes](https://github.com/Peppe289/builder-linux/commit/77777e8a7d4f86bcbc5583625f830be421f59a8e) we need to use CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 flags:
> 
> Note that only LLVM=1 should be necessary; it implies the rest.
> 
> https://docs.kernel.org/kbuild/llvm.html#llvm-utilities
> 
> (assuming you're not on some ancient kernel version)

thanks for the reference.  I currently need the config for the latest rc, so assumptions are correct.  I will fix asap. Thx.
